name: Build and run tests

on: [push]

jobs:
  build-test:
    name: Build and test package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 23.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn prettier-check
      - run: yarn lint-check
      - run: yarn build-lib
      - run: yarn type-check-app
      - run: yarn test-lib
      - run: yarn test-app
